baseURL = "https://watiko.net/"
languageCode = "ja-jp"
title = "TypoTypoTypo"

googleAnalytics = "G-DF9X93R3ZP"

contentDir = "posts"
enableGitInfo = true
hasCJKLanguage = true
publishdir = "public"

theme = "PaperMod"

[minify]
disableXML = true
minifyOutput = true

[params]
mainSections = ["post", "posts"]

author = "watiko"

disableSpecial1stPost = true
showBreadCrumbs = false
showCodeCopyButtons = true
showPostNavLinks = true
showReadingTime = true
showToc = true

[params.homeInfoParams]
content = "気になったこととかやったこととかをメモしておく場所"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/watiko"

[[params.socialIcons]]
name = "github"
url = "https://github.com/watiko"

[[params.socialIcons]]
name = "rss"
url = "index.xml"

[params.editPost]
appendFilePath = true
text = "Suggest Changes"
url = "https://github.com/watiko/blog/tree/master/posts"

[author]
name = "watiko"
