baseURL = "https://watiko.net/"
languageCode = "ja-jp"
title = "TypoTypoTypo"

publishdir = "public"
contentDir = "posts"
hasCJKLanguage = true

theme = "beautifulhugo"

[Params]
  useHLJS = true
  logo = "/image/logo.png"

[Author]
  name = "watiko"
  website = "watiko.net"
  github = "watiko"
  twitter = "watiko"
