baseURL = "https://watiko.net/"
languageCode = "ja-jp"
title = "TypoTypoTypo"

googleAnalytics = "UA-18231761-2"

enableGitInfo = true
publishdir = "public"
contentDir = "posts"
hasCJKLanguage = true

theme = "beautifulhugo"

# use Chroma
pygmentsUseClasses = true
pygmentsCodeFences = true

[Params]
  logo = "/image/logo.png"
  mainSections = ["post","posts"]

[Author]
  name = "watiko"
  website = "watiko.net"
  github = "watiko"
  twitter = "watiko"
