name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: setup hugo
      run: |
        cd /tmp
        HUGO_DEB="hugo_${HUGO_VERSION}_Linux-64bit.deb"
        wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DEB}"
        sudo dpkg -i "$HUGO_DEB"
        hugo version
      env:
        HUGO_VERSION: 0.59.1
    - name: build test
      run: |
        npm ci
        npm run website
